# PythonからMySQLを操作してJUNのDB解析

## MySQLアクセス準備

In [82]:
import pandas as pd
import numpy as np
#import sqlalchemy
#from configparser import ConfigParser

In [83]:
import mysql.connector
#from connector.mysql import MySQL

config = { 'host' : '127.0.0.1',
           'user' : 'root',
           'password' : 'bm0lP2vryl75cPiu',
           'port' : 3332,
           'database' : 'master'}

class MySQL():
    def __init__(self, config):
        u"""
        :param config: 接続設定を格納した辞書
        """
        self.config = config
        self.conn = None
        if config is not None:
            self.connect()

    def connect(self, config=None):
        u"""
        MySQLに接続する。
        :return:
        """
        if config is None:
            config = self.config
        conn = mysql.connector.connect(**config)
        self.conn = conn
        return conn
mysql = MySQL(config)

In [3]:
pd.set_option("display.max_columns", 100)

## TABLE: item
データ数：339093---(0.339M)
* What
    * Brand (item.brand)
    * Item category (item.item_category)
    * Year?? (item.year)
    * Season?? (item.season)
    * Zone?? (item.zone)
    * Cost rate (item.cost_rate) (原価率)

### データ数取得

In [4]:
cur = mysql.conn.cursor()
cur.execute('SELECT COUNT(*) FROM item')

num_item = cur.fetchall()
print(num_item)

[(339093,)]

### itemテーブルのデータ確認

In [144]:
sql = """
        SELECT * FROM item LIMIT 1000, 500000
      """
df_item = pd.read_sql(sql, mysql.conn)

### レディースブランド

In [156]:
ladies = df_item.iloc[:,:3][df_item.name.str.contains('スカート')]
ladies.drop_duplicates(subset = 'brand').brand.values

array(['AA', 'AC', 'AN', 'AQ', 'BH', 'BJ', 'BO', 'BP', 'BV', 'BW', 'BX',
       'BY', 'EK', 'EO', 'ER', 'ES', 'EU', 'FL', 'FN', 'FO', 'GA', 'GC',
       'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GK', 'GL', 'GM', 'GN', 'GR',
       'GT', 'GU', 'GW', 'GX', 'LF', 'NB', 'NJ', 'OL', 'RC', 'RJ', 'RR',
       'RS', 'SH', 'TI', 'TS', 'UM', 'ZP'], dtype=object)

In [171]:
df_item.iloc[:,:3].query("brand == 'BP'")

       part_no                name brand
27763  BPA0000                シューズ    BP
27764  BPA1800             ドットパンプス    BP
27765  BPA1801      Tストラップウェッジサンダル    BP
27766  BPA1802  リボン付オープントゥフラットシューズ    BP
27767  BPA1803          バイカラー麻パンプス    BP
27768  BPA1804     バイカラーＴストラップサンダル    BP
27769  BPA1805       ウッドソールリボンサンダル    BP
27770  BPA1806       エスパオープントゥサンダル    BP
27771  BPA1807       くるみリングねじりミュール    BP
27772  BPA1808        ウェッジトラッドシューズ    BP
27773  BPA1811       麻*エナメルバレーシューズ    BP
27774  BPA1820       スクエアモチーフ付サンダル    BP
27775  BPA1821      アンクルストラップ付サンダル    BP
27776  BPA1822          レースバレエシューズ    BP
27777  BPA1823            スクエアパンプス    BP
27778  BPA1850       ビジュー付パンプス20MM    BP
27779  BPA1851     太バックルオープントゥパンプス    BP
27780  BPA1853          合皮ジョッキーブーツ    BP
27781  BPA1854   バックリボン付折り返しミドルブーツ    BP
27782  BPA1855      編み上げ２ＷＡＹファーブーツ    BP
27783  BPA1857      合皮変型切替ジョッキーブーツ    BP
27784  BPA1900     ピッグスウエードショートブーツ    BP
27785  BPA1901        ビジュー付サテンパンプス    BP
27786  BPA1902     Ｔストラップバタフライパンプス    BP
27787  BPA1903         レーザーカットサンダル    BP
27788  BPA1904        ST入りエナメルパンプス    BP
27789  BPA1906     変りウェッジアンクルストラップ    BP
27790  BPA5800        ウェッジトラッドシューズ    BP
27791  BPA5801    ＲＡＳビーズ使いフラットシューズ    BP
27792  BPA5802    ＲＡＳキルティングショートブーツ    BP
...        ...                 ...   ...
32337  BPZ5941       天然石使いロングネックレス    BP
32338  BPZ5942      ストライプ柄サテン地シュシュ    BP
32339  BPZ5943        マリン柄シフォンシュシュ    BP
32340  BPZ5944          花柄シフォンシュシュ    BP
32341  BPZ5945   メタル花モチーフショートネックレス    BP
32342  BPZ5946    メタル花モチーフロングネックレス    BP
32343  BPZ5947       メタル花モチーフ使いブレス    BP
32344  BPZ5950    錨モチーフ使いショートネックレス    BP
32345  BPZ5951    錨モチーフロープロングネックレス    BP
32346  BPZ5952      錨モチーフロープコンビブレス    BP
32347  BPZ5954       フラワー＆ビーズ付ヘアゴム    BP
32348  BPZ5955            フラワーヘアゴム    BP
32349  BPZ5957       チェーン付マリンエンブレム    BP
32350  BPZ5958        リボン付マリンエンブレム    BP
32351  BPZ6900       オパール刺繍晴雨折りたたみ    BP
32352  BPZ6901           スタープリント雨傘    BP
32353  BPZ6902    プチフリルショート晴雨折りたたみ    BP
32354  BPZ6903      ストライプピコレース晴雨雨傘    BP
32355  BPZ6904       アートフラワープリント雨傘    BP
32356  BPZ7902     ANCREレース付WALLET    BP
32357  BPZ7903     ANCREレース＆ハラコポーチ    BP
32358  BPZ8900             ドッグチャーム    BP
32359  BPZ8901            キャットチャーム    BP
32360  BPZ8902            ガールズチャーム    BP
32361  BPZ8903            ボーイズチャーム    BP
32362  BPZ9800  パール玉*アクリルショートネックレス    BP
32363  BPZ9801        ちりばめパールネックレス    BP
32364  BPZ9802      ２ＷＡＹレース付きコサージュ    BP
32365  BPZ9900       フリンジ付パールネックレス    BP
32366  BPZ9901       ドット柄フラワーコサージュ    BP

[4604 rows x 3 columns]

### csvファイル作成 or 読み込み
Item: brand, item_category, year, season, zone, cost_rate

In [137]:
import os.path

filename = 'jun_item.csv'

if os.path.isfile(filename):
    df_item = pd.read_csv(filename)#, header=None)
    df_item = df_item.iloc[:,1:]
else:
    sql = """
            SELECT brand, item_category, year, season, zone, cost_rate FROM item
            """
    df_item = pd.read_sql(sql, mysql.conn)

    df_item.to_csv(filename)

### データ確認

In [70]:
df_item.loc[1000::2500]

       brand item_category  year season  zone  cost_rate
1000      AA             D  2011      A    10       35.0
3500      AA             D  2010      B    10       33.8
6000      AA             D  2008      B    10       35.5
8500      AA             M  2009      A    30       30.0
11000     AA             P  2008      C    10       63.9
13500     AA             W  2014      A    90       27.1
16000     AN             K  2010      A    90       31.4
18500     AN             S  2014      B    90       32.4
21000     AO             X  2015      A    99       29.8
23500     BB             M  2013      A    90       40.3
26000     BH             I  2015      C    90       60.0
28500     BO             I  2017      C    90       57.2
31000     BP             K  2008      B    10       30.2
33500     BV             A  2013      A    10       30.6
36000     BV             E  2014      B    10       30.3
38500     BV             K  2011      A    10       34.2
41000     BV             M  2013      B    10       30.0
43500     BV             R  2015      B    10       45.0
46000     BV             X  2015      A    10       30.4
48500     BV             Z  2010      A    10       33.3
51000     BW             D  2015      B    90       49.3
53500     BW             M  2011      A    90       60.0
56000     BW             Y  2008      A    19       40.0
58500     BX             L  2013      B    20       76.1
61000     BX             Z  2008      C    60       45.0
63500     EC             I  2013      C    90       60.0
66000     EK             I  2017      C    90       65.0
68500     EK             I  2017      C    90       54.0
71000     EK             Q  2015      C    90       60.0
73500     EK             Z  2016      C    90       36.7
...      ...           ...   ...    ...   ...        ...
266000    GM             M  2011      A    10       41.8
268500    GM             U  2011      B    10       33.7
271000    GR             Z  2017      A    99       33.8
273500    GT             Z  2015      C    90       35.4
276000    GW             H  2017      A    90       37.5
278500    GW             Z  2014      A    90       54.7
281000    KU             I  2016      B    90       34.3
283500    LF             E  2014      B    90       32.2
286000    LS             N  2016      B    90       40.0
288500    NN             A  2016      B    20       60.0
291000    OL             I  2013      C    90       60.0
293500    OM             M  2015      A    90       55.0
296000    PG             I  2016      C    70       70.0
298500    PO             X  2014      C    30       31.6
301000    RR             N  2012      B    90       17.7
303500    SF             D  2013      C    90       70.0
306000    SF             P  2015      C    90       67.5
308500    SF             P  2016      C    90       67.9
311000    SH             B  2016      C    90       60.0
313500    SH             I  2015      C    90       55.0
316000    SH             I  2017      C    90       60.0
318500    SH             O  2015      B    90       62.0
321000    TI             I  2014      C    90       31.3
323500    TS             H  2015      C    90       25.0
326000    UM             Z  2009      B    11       42.2
328500    ZP             M  2017      A    90       55.0
331000    ZP             Z  2015      B    90       31.5
333500    ZR             K  2010      C    40       59.5
336000    ZR             Z  2014      C    90       80.0
338500    ZV             B  2009      C     0       58.0

[136 rows x 6 columns]

## TABLE: receiving
データ数：35422637---(35.4M)

In [114]:
cur = mysql.conn.cursor()
cur.execute('SELECT COUNT(*) FROM receiving')

num_receiving = cur.fetchall()
num_receiving

[(35422637,)]

In [31]:
sql_rec = """
        SELECT * FROM receiving LIMIT 10000
      """
df_read_rec = pd.read_sql(sql_rec, mysql.conn)

In [32]:
df_read_rec.head(10)

,brand,year,month,date,shop_id,part_no,color,size_id,unknown,item_category,product_year,product_season,num_recieve,num_return,sales_div
0,GA,2015,01,20150103.0,103897GH,GAH1409,60,36,05,H,2014,B,1,0,0
1,GA,2015,01,20150103.0,103897GH,GAM1413,23,38,06,M,2014,B,2,0,0
2,GA,2015,01,20150103.0,103897GH,GAM1419,10,38,06,M,2014,B,1,0,0
3,GA,2015,01,20150103.0,103897GH,GAM1425,80,38,06,M,2014,B,1,0,0
4,GA,2015,01,20150103.0,103897GH,GAM1458,01,38,06,M,2014,B,1,0,0
5,GA,2015,01,20150103.0,103897GH,GAM1458,44,38,06,M,2014,B,1,0,0
6,GA,2015,01,20150103.0,103897GH,GAM3415,43,38,06,M,2014,B,1,0,0
7,GA,2015,01,20150103.0,103897GH,GAM6451,10,38,06,M,2014,B,3,0,0
8,GA,2015,01,20150103.0,103897GH,GAM6453,40,38,06,M,2014,B,3,0,0
9,GA,2015,01,20150103.0,103897GH,GAM6467,07,38,06,M,2014,B,1,0,0

## TABLE: member
データ数：7058393---(7.06M)

* Who
    * Gender（member.gender）
    * Age（member.birthdayから算出）
    * 居住地（member.pref_cd or member.zipcode）

### データ数確認

In [12]:
cur = mysql.conn.cursor()
cur.execute('SELECT COUNT(*) FROM member')
cur.fetchall()

[(7058393,)]

### memberテーブルの確認

In [48]:
sql_mem = """
        SELECT * FROM member LIMIT 10000
        """
df_member_original = pd.read_sql(sql_mem, mysql.conn)
df_member_original.head(100)

,member_id,status,gender,birthday,birthday_mm,pref_cd,zipcode,expire_date,add_date,mod_date
0,-9578401,1,0,,0,00,,20160331,20150402 060235,20160411 000001
1,0$014000,1,0,,0,00,,20190106,20180108 060249,20180108 060249
2,00000380,1,0,,0,00,,20150613,20140615 060859,20150624 000001
3,00004200,1,0,,0,00,,20180812,20170814 060210,20170814 060210
4,00101824,1,0,,0,00,,20170611,20160613 060242,20170622 000001
5,001900A7,1,0,,0,00,,20161215,20151217 060335,20161226 000001
6,002900A5,1,0,,0,00,,20160604,20150606 060321,20160615 000001
7,004700A3,1,0,,0,00,,20140904,20130906 060445,20140915 000001
8,005500A2,1,0,,0,00,,20140702,20130704 060832,20130704 060832
9,005700A0,1,0,,0,00,,20180218,20170220 062410,20170220 062410
10,00778514,1,0,,0,00,,20121015,20111017 060604,20111017 060604
11,009500A4,1,0,,0,00,,20170206,20160208 060620,20170217 000001
12,01004464,1,0,,0,00,,20140922,20130924 060819,20141003 000001
13,01102102,1,0,,0,00,,20161216,20151218 060350,20151218 060350
14,015000A6,1,0,,0,00,,20141123,20131125 060552,20141204 000001
15,01512144,1,0,,0,00,,20120604,20110606 060702,20110606 060702
16,016000A4,1,0,,0,00,,20160207,20150209 060421,20160218 000001
17,02015808,1,0,,0,00,,20111003,20101005 060401,20101125 211159
18,02022705,1,0,,0,00,,20131122,20121124 060904,20121124 060904
19,02500023,1,0,,0,00,,20130430,20120419 060416,20120419 060416
20,02600039,1,0,,0,00,,20130606,20120418 060407,20120418 060407
21,04039632,1,0,,0,00,,20170430,20160502 060237,20170511 000001
22,04321006,1,0,,0,00,,20150704,20140706 061101,20150715 000001
23,04940474,1,0,,0,00,,20120220,20110222 060313,20110222 060313
24,05221460,1,0,,0,00,,20130427,20120429 060728,20120429 060728
25,07024508,1,0,,0,00,,20180414,20170416 060242,20170416 060740
26,07331002,1,0,,0,00,,20180622,20170624 060243,20170624 060243
27,07562705,1,0,,0,00,,20180601,20170603 060155,20170603 060155
28,09291006,1,0,,0,00,,20160701,20150703 060447,20160712 000001
29,10000032,1,0,,0,00,,20150426,20140428 062628,20150507 000001
...,...,...,...,...,...,...,...,...,...,...
70,10001253,1,2,19650729,7,12,2750011,20150408,20100919 060932,20170419 000658
71,10001287,0,2,19510330,3,09,3214334,20141012,20070525 152839,20131014 061838
72,10001329,1,1,19500424,4,13,1820023,20070425,20070511 174648,20101125 211159
73,10001352,0,2,19610928,9,13,1640012,20150815,20070428 133238,20140818 160817
74,10001360,0,2,19461126,11,11,3360932,20140926,20070508 154736,20140924 220223
75,10001386,0,2,19530312,3,,1850082,20150504,20070510 122210,20150321 092635
76,10001394,0,2,19430724,7,13,1500021,20141123,20070510 122211,20131204 172200
77,10001428,0,2,19410122,1,13,1430011,20150521,20070428 133237,20180105 112458
78,10001436,0,1,19560608,6,13,1120013,20141123,20070510 122211,20131204 172427
79,10001485,0,2,19560307,3,14,2120015,20161102,20070510 122208,20160930 113919
80,10001527,1,1,19620712,7,11,3440002,20180829,20070510 122210,20170831 060344
81,10001535,0,2,19480109,1,09,3210954,20160107,20070510 122208,20150110 102121
82,10001543,1,2,19600324,3,14,2540904,20180209,20070510 122208,20170211 061905
83,10001568,0,2,19590102,1,13,1128560,20150501,20070510 122206,20140503 235856
84,10001592,1,0,,0,00,,20131007,20121009 061122,20131018 000001
85,10001618,1,0,,0,00,,20140428,20130514 142538,20140509 000001
86,10001642,1,2,19490317,3,11,3630006,20130511,20070511 174656,20101125 211159
87,10001659,1,0,,0,00,,20161128,20140418 061322,20161209 000001
88,10001675,0,2,19620328,3,11,3300064,20140903,20070503 063554,20101125 211159
89,10001709,0,1,19560427,4,13,1160002,20141104,20070428 133238,20171106 210807
90,10001717,0,2,19581201,12,11,3520011,20140724,20070510 122203,20160930 172130
91,10001741,1,2,19830224,2,11,3430041,20160319,20070518 071020,20160330 000001
92,10001808,1,1,19540903,9,11,3340052,20070521,20070608 162212,20101125 211159
93,10001810,1,0,,0,00,,20160728,20150730 061651,20160808 000001
94,10001824,0,2,19730202,2,12,2610011,20140825,20070520 071020,20140715 134042
95,10001832,1,2,19690829,8,14,2110036,20070521,20070608 162211,20101125 211159
96,10001840,1,0,,0,00,,20130904,20120906 060526,20120906 060526
97,10001857,1,0,,0,00,,20121117,20111119 060635,20111119 060635
98,10001865,1,0,,0,00,,20141022,20131024 061053,20141102 000001
99,10001873,1,2,19670130,1,13,1240021,20111009,20070521 071024,20101125 211159

### sales.member_idとmemberの結合（whoの作成）

In [200]:
df1 = df_member#.loc[:500000,['member_id', 'gender', 'birthday']].query("birthday != ''").head(100000)
#df2 = df_sales#.loc[:500000, ['member_id', 'shop_id']].query("member_id != '00000000'").head(100000)
df2 = df_sales_original.loc[:,['sales_date','member_id', 'part_no', 'color', 
                               'size_id', 'unit_price', 'list_price', 'shop_id']]
df_merge = pd.merge(df1, df2, on = 'member_id', how = 'outer')
df_merge.tail(100)

,member_id,gender,birthday,pref_cd,zipcode,sales_date,part_no,color,size_id,unit_price,list_price,shop_id
28980350,F3039457,NaN,NaN,NaN,NaN,20170330.0,GDS1711,1.0,38,3900.0,3900.0,108891GD
28980351,F3039457,NaN,NaN,NaN,NaN,20170809.0,BVS3701,25.0,S,3900.0,3900.0,103289BV
28980352,46776100,NaN,NaN,NaN,NaN,20170331.0,BVF1708,7.0,F,1350.0,1500.0,102091GL
28980353,46776100,NaN,NaN,NaN,NaN,20170331.0,BVS1705,41.0,S,2808.0,3900.0,102091GL
28980354,46776100,NaN,NaN,NaN,NaN,20170917.0,GDK5709,6.0,40,2900.0,2900.0,108891GD
28980355,46776100,NaN,NaN,NaN,NaN,20170917.0,GDS5721,40.0,38,3900.0,3900.0,108891GD
28980356,46776100,NaN,NaN,NaN,NaN,20170919.0,GDH5750,40.0,38,2900.0,2900.0,102092GD
28980357,M5231602,NaN,NaN,NaN,NaN,20170402.0,GDH1722,48.0,38,2900.0,2900.0,151090GD
28980358,M5231602,NaN,NaN,NaN,NaN,20170409.0,GDC1728,48.0,38,3900.0,3900.0,108891GD
28980359,M5910551,NaN,NaN,NaN,NaN,20170409.0,GDC1706,40.0,36,4400.0,4400.0,108891GD
28980360,M5910577,NaN,NaN,NaN,NaN,20170409.0,GDK1714,40.0,38,2900.0,2900.0,108891GD
28980361,M5910536,NaN,NaN,NaN,NaN,20170409.0,GDO1706,7.0,38,6400.0,6400.0,108891GD
28980362,M6190138,NaN,NaN,NaN,NaN,20170513.0,GDH1739,48.0,38,2900.0,2900.0,108891GD
28980363,M6190088,NaN,NaN,NaN,NaN,20170513.0,GDV2705,40.0,38,6900.0,6900.0,108891GD
28980364,G8304185,NaN,NaN,NaN,NaN,20170518.0,GDH1737,33.0,38,3900.0,3900.0,108996GD
28980365,G8304185,NaN,NaN,NaN,NaN,20170917.0,GDH5725,16.0,38,2900.0,2900.0,108891GD
28980366,M7291679,NaN,NaN,NaN,NaN,20170522.0,BVE1722,1.0,F,4050.0,4500.0,151092BV
28980367,M7291679,NaN,NaN,NaN,NaN,20170526.0,GII3786,64.0,F,380.0,380.0,108891GD
28980368,M7291679,NaN,NaN,NaN,NaN,20170526.0,GIZ0703,90.0,F,900.0,900.0,108891GD
28980369,M6986790,NaN,NaN,NaN,NaN,20170526.0,GDC1722,40.0,38,3900.0,3900.0,108891GD
28980370,M6986790,NaN,NaN,NaN,NaN,20170526.0,GDC1740,27.0,38,3900.0,3900.0,108891GD
28980371,M6986790,NaN,NaN,NaN,NaN,20170526.0,GDC1773,1.0,38,4900.0,4900.0,108891GD
28980372,M6986790,NaN,NaN,NaN,NaN,20170526.0,GDE1733,48.0,38,5900.0,5900.0,108891GD
28980373,M6191086,NaN,NaN,NaN,NaN,20170526.0,GDH1721,44.0,38,3900.0,3900.0,108891GD
28980374,M6986766,NaN,NaN,NaN,NaN,20170526.0,GDH1740,75.0,38,2900.0,2900.0,108891GD
28980375,M6986808,NaN,NaN,NaN,NaN,20170526.0,GDH4712,10.0,38,4200.0,4200.0,108891GD
28980376,M6191060,NaN,NaN,NaN,NaN,20170526.0,GDK1714,40.0,38,2900.0,2900.0,108891GD
28980377,M6191060,NaN,NaN,NaN,NaN,20170526.0,GDM1768,10.0,38,1900.0,1900.0,108891GD
28980378,M6986816,NaN,NaN,NaN,NaN,20170526.0,GDM1768,44.0,38,1900.0,1900.0,108891GD
28980379,M6986782,NaN,NaN,NaN,NaN,20170526.0,GDS1733,52.0,38,3900.0,3900.0,108891GD
...,...,...,...,...,...,...,...,...,...,...,...,...
28980420,M9802390,NaN,NaN,NaN,NaN,20170922.0,GDC5711,36.0,38,3900.0,3900.0,108891GD
28980421,M9802259,NaN,NaN,NaN,NaN,20170922.0,GDC5721,25.0,36,3900.0,3900.0,108891GD
28980422,M9802259,NaN,NaN,NaN,NaN,20170922.0,GDH5741,44.0,38,2900.0,2900.0,108891GD
28980423,M9802259,NaN,NaN,NaN,NaN,20170922.0,GIZ6708,27.0,F,1700.0,1700.0,108891GD
28980424,M9802499,NaN,NaN,NaN,NaN,20170922.0,GDH5723,40.0,38,3900.0,3900.0,108891GD
28980425,M9802473,NaN,NaN,NaN,NaN,20170922.0,GDH5738,15.0,38,2900.0,2900.0,108891GD
28980426,M9802234,NaN,NaN,NaN,NaN,20170922.0,GDM5709,80.0,40,2900.0,2900.0,108891GD
28980427,M9802408,NaN,NaN,NaN,NaN,20170922.0,GDM5718,40.0,38,1900.0,1900.0,108891GD
28980428,M9802481,NaN,NaN,NaN,NaN,20170922.0,GDM6709,1.0,38,2900.0,2900.0,108891GD
28980429,M9802481,NaN,NaN,NaN,NaN,20170922.0,GDM6714,52.0,38,3900.0,3900.0,108891GD
28980430,P1275820,NaN,NaN,NaN,NaN,20171013.0,GDC5723,52.0,40,3120.0,3900.0,108891GD
28980431,P1275879,NaN,NaN,NaN,NaN,20171013.0,GDC5734,30.0,38,3900.0,3900.0,108891GD
28980432,P1275861,NaN,NaN,NaN,NaN,20171013.0,GDM5708,48.0,38,2900.0,2900.0,108891GD
28980433,P1275887,NaN,NaN,NaN,NaN,20171013.0,GDS5701,1.0,36,2900.0,2900.0,108891GD
28980434,P1275838,NaN,NaN,NaN,NaN,20171013.0,GIA6702,40.0,37,4200.0,4200.0,108891GD
28980435,P1374110,NaN,NaN,NaN,NaN,20171013.0,GIN6710,15.0,F,1900.0,1900.0,108891GD
28980436,P1374110,NaN,NaN,NaN,NaN,20171013.0,GWC2716,65.0,36,13000.0,13000.0,109095GG
28980437,P1275218,NaN,NaN,NaN,NaN,20171020.0,GDC5738,40.0,38,2900.0,2900.0,108891GD
28980438,P1275184,NaN,NaN,NaN,NaN,20171020.0,GDE5727,1.0,36,3900.0,3900.0,108891GD
28980439,P1275200,NaN,NaN,NaN,NaN,20171020.0,GDH5735,40.0,36,3120.0,3900.0,108891GD
28980440,P1275143,NaN,NaN,NaN,NaN,20171020.0,GDS5721,9.0,36,3120.0,3900.0,108891GD
28980441,P2984578,NaN,NaN,NaN,NaN,20171124.0,GDE5777,1.0,36,4900.0,4900.0,108891GD
28980442,P2984446,NaN,NaN,NaN,NaN,20171124.0,GDH5772,49.0,38,2610.0,2900.0,108891GD
28980443,P2984446,NaN,NaN,NaN,NaN,20171124.0,GDM5714,86.0,36,2610.0,2900.0,108891GD
28980444,P2984453,NaN,NaN,NaN,NaN,20171124.0,GDK5709,42.0,38,1980.0,2900.0,108891GD
28980445,P2984420,NaN,NaN,NaN,NaN,20171124.0,GDK5721,27.0,38,3510.0,3900.0,108891GD
28980446,P2984552,NaN,NaN,NaN,NaN,20171124.0,GDM5714,27.0,38,2610.0,2900.0,108891GD
28980447,P2984396,NaN,NaN,NaN,NaN,20171124.0,GDM5776,40.0,38,2610.0,2900.0,108891GD
28980448,P2984396,NaN,NaN,NaN,NaN,20171124.0,GIZ6720,40.0,F,1710.0,1900.0,108891GD
28980449,P2984412,NaN,NaN,NaN,NaN,20171124.0,GIA6790,1.0,36,4900.0,4900.0,108891GD

In [201]:
filename = 'jun_needed_data.csv'
df_merge.to_csv(filename)

### csvファイル作成 or 読み込み
Member: gender, birthday, pref_cod, zip_code

In [120]:
import os.path

#filename = 'jun_member.csv'
filename = 'jun_member_add_member_id.csv'

if os.path.isfile(filename):
    df_member = pd.read_csv(filename).iloc[:,1:]
    
else:
    if filename = 'jun_meber.csv':
        sql_sls = """
            SELECT member_id, gender, birthday, pref_cd, zipcode FROM member
            """
        df_member = pd.read_sql(sql_sls, mysql.conn)
    elif filename = 'jun_member_add_member_id.csv':
        sql_sls = """
                SELECT member_id, gender, birthday, pref_cd, zipcode FROM member
                """
        df_member = pd.read_sql(sql_sls, mysql.conn)
    else:
        print("ファイル名を確認してください。")
        break

    df_member.to_csv(filename)

### データ確認

In [125]:
df_member.drop_duplicates(subset = 'zipcode')

        member_id gender  birthday pref_cd  zipcode
0        -9578401      0                00
30       10000081      2  19580911      11  3430845
31       10000099      2  19400316      11  3440021
33       10000115      2  19720708      11  3590027
34       10000123      2  19620423      13  1320034
35       10000131      2  19740608      13  1120011
36       10000156      2  19540718      11  3300074
37       10000164      2  19610414      13  1740052
38       10000180      2  19501126      09  3291311
39       10000198      2  19580717      14  2220003
40       10000222      2  19540420      11  3430026
41       10000230      2  19731113      09  3200851
42       10000263      2  19690817      13  1420053
45       10000362      2                13  1040051
46       10000396      1  19650414      13  1120014
47       10000404      2  19521217      11  3350011
48       10000412      2  19680203      09  3200037
49       10000446      2  19630320      11  3350005
51       10000479      2  19670625      13  1760005
52       10000503      2  19641024      13  1340088
53       10000529      2  19700326      09  3211277
55       10000743      2  19490701      13  1110023
56       10000750      2  19580304      13  1080075
57       10000776      1  19781006      09  3270843
58       10000834      1  19410410      12  2600044
59       10000842      1  19411005      08  3050031
60       10000891      1  19680827      09  3230012
61       10000941      1  19710520      14  2400012
62       10000982      2  19401222      11  3330802
65       10001055      2  19430206      14  2291111
...           ...    ...       ...     ...      ...
6934638  R1656173      1  19830817      17  9230027
6934948  R1659300      1  19881223      42  8596145
6935017  R1660019      1  19730429      22  4371507
6935134  R1661199      1  19810105      19  4091502
6935296  R1662817      1  19830209      21  5032407
6936620  R1676106      1  19811219      12  2992223
6936753  R1677443      1  19861015      17  9250376
6936967  R1679597      1  19800419      25  5291174
6937342  R1683359      1  19800124      20  3842105
6937386  R1683797      1  19700323      26  6240853
6937821  R1688176      1  19631201      12  2940812
6937986  R1689851      1  19740101      41  8491422
6938013  R1690123      1  19811002      16  9360875
6938376  R1693762      1  19880918      13  1140211
6938980  R1699850      1  19820720      11  3690314
6939144  R1701516      1  19681011      05  0191301
6939461  R1704718      1  19830910      45  8850051
6939760  R1707711      1  19830609      01  0861108
6940109  R1711234      1  19890405      15  9495213
6940155  R1711705      1  19710628      28  6638185
6940691  R1717074      1  19830904      08  3040069
6943925  R1749465      1  19881019      37  7680023
6948514  R1795401      1  19741215      22  4170813
6950279  R1813071      1  19850620      33  7128026
6966583  R1976118      1  19800807      23  4901424
6974710  R2057371      1  19710310      22  4270001
6979032  R2100593      1  19830430      30  6495336
7010445  S1014694      2  19870313      25  5260844
7038317  S1293603      2  19780904      28  6792167
7046979  S1380228      2  19840901      37  7620018

[68266 rows x 5 columns]

## TABLE: sales
データ数: 24320102---(24.30M)

* Who
    * Member ID (sales.member_id)
* What
    * SKU
        * sales.part_no, sales.color, sales.size_idでユニーク
    * Color (sales.color)
    * Size (sales.size_id)
    * Actual Price (sales.unit_price)
    * List Price (sales.list_price)

* Where
    * Shop ID (sales.shop_id)

### csvファイル作成 or 読み込み
salesのうち全てのカラムを取り出したもの

In [81]:
sql_sls = """
            SELECT * FROM sales LIMIT 1000, 10
            """
df = pd.read_sql(sql_sls, mysql.conn)
pd.to_datetime(df['sales_date'])
#df.dtypes

0   2015-01-01
1   2015-01-01
2   2015-01-01
3   2015-01-01
4   2015-01-01
5   2015-01-01
6   2015-01-01
7   2015-01-01
8   2015-01-01
9   2015-01-01
Name: sales_date, dtype: datetime64[ns]

In [197]:
import os.path

filename = 'jun_sales.csv'

if os.path.isfile(filename):
    df_sales_original = pd.read_csv(filename).iloc[:,1:]#, header=None)
else:
    sql_sls = """
            SELECT * FROM sales 
            """
    df_sales_original = pd.read_sql(sql_sls, mysql.conn)

    df_sales_original.to_csv(filename)

### salesテーブルの確認

In [199]:
df_sales_original.head(100)

,sales_date,sales_time,shop_id,part_no,color,size_id,unit_price,num_sales,sales_amount,list_price,cash_register_no,receipt_no,error_segment,member_id,create_date,create_time,create_seq
0,20150101,21:52,100003BV,BVA4408,1,M,2240,1,2240,6400,88,3635,2,00000000,20150103,12303,227508
1,20150101,21:52,100003BV,BVC3486,25,M,1330,1,1330,3800,88,3487,2,00000000,20150103,12303,227486
2,20150101,21:52,100003BV,BVC4413,1,S,1260,1,1260,4200,88,3617,2,00000000,20150103,12303,227504
3,20150101,21:52,100003BV,BVE4452,31,M,1645,1,1645,4700,88,3501,2,00000000,20150103,12303,227490
4,20150101,21:57,100003BV,BVH4406,31,M,1330,1,1330,3800,89,947,2,00000000,20150104,12232,211489
5,20150101,21:52,100003BV,BVK3465,8,L,1330,1,1330,3800,88,3585,2,00000000,20150103,12303,227499
6,20150101,21:52,100003BV,BVK4413,60,M,980,1,980,2800,88,3619,2,00000000,20150103,12303,227505
7,20150101,21:52,100003BV,BVM3416,10,M,910,1,910,2600,88,3637,2,00000000,20150103,12303,227509
8,20150101,21:52,100003BV,BVM3453,15,M,980,1,980,2800,88,3491,2,00000000,20150103,12303,227487
9,20150101,21:52,100003BV,BVM3474,8,M,1715,1,1715,4900,88,3575,2,00000000,20150103,12303,227493
10,20150101,21:57,100003BV,BVM3474,10,M,1715,1,1715,4900,89,947,2,00000000,20150104,12232,211488
11,20150101,21:52,100003BV,BVM3475,8,M,1330,1,1330,3800,88,3573,2,00000000,20150103,12303,227492
12,20150101,21:57,100003BV,BVM3475,10,M,1330,1,1330,3800,89,1139,2,00000000,20150104,12232,211492
13,20150101,21:57,100003BV,BVM3475,17,M,1330,1,1330,3800,89,1141,2,00000000,20150104,12232,211495
14,20150101,21:57,100003BV,BVM3475,63,M,1330,1,1330,3800,89,1141,2,00000000,20150104,12232,211496
15,20150101,21:57,100003BV,BVM3476,16,M,1645,1,1645,4700,89,1137,2,00000000,20150104,12232,211491
16,20150101,21:57,100003BV,BVM3479,7,M,665,1,665,1900,89,1141,2,00000000,20150104,12232,211498
17,20150101,21:57,100003BV,BVM4468,10,M,980,1,980,2800,89,1141,2,00000000,20150104,12232,211499
18,20150101,21:52,100003BV,BVR3413,10,M,525,1,525,1500,88,3575,2,00000000,20150103,12303,227494
19,20150101,21:57,100003BV,BVS3415,2,S,1645,1,1645,4700,89,1141,2,00000000,20150104,12232,211500
20,20150101,21:52,100003EU,EUA7434,80,24.5,7000,1,7000,10000,88,3623,2,00000000,20150103,12303,227511
21,20150101,21:52,100003GA,GAE1411,6,38,5600,1,5600,16000,88,3477,2,00000000,20150103,12303,227515
22,20150101,21:52,100003GA,GAE3491,1,38,10150,1,10150,29000,88,3475,2,00000000,20150103,12303,227514
23,20150101,21:52,100003GD,GDC5406,6,38,1330,1,1330,3800,88,3611,2,00000000,20150103,12303,227551
24,20150101,21:57,100003GD,GDC5451,1,38,1470,1,1470,4200,89,1083,2,00000000,20150104,12232,211503
25,20150101,21:52,100003GD,GDC5475,16,38,1645,1,1645,4700,88,3553,2,00000000,20150103,12303,227541
26,20150101,21:52,100003GD,GDF5406,7,38,665,1,665,1900,88,3553,2,00000000,20150103,12303,227545
27,20150101,21:52,100003GD,GDM5407,7,38,1470,1,1470,4200,88,3599,2,00000000,20150103,12303,227546
28,20150101,21:57,100003GD,GDM5407,30,38,1470,1,1470,4200,89,1199,2,00000000,20150104,12232,211506
29,20150101,21:52,100003GD,GDM5410,7,38,1470,1,1470,4200,88,3493,2,00000000,20150103,12303,227519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,20150101,12:03,100107GG,BVC3422,2,M,2115,1,2115,4700,1,7081,2,00000000,20150102,12323,90164
71,20150101,11:32,100107GG,BVE0414,28,M,2394,1,2394,3800,1,7064,2,00000000,20150102,12323,90148
72,20150101,16:02,100107GG,BVE1400,45,M,1890,1,1890,4200,1,7212,2,00000000,20150102,12323,90265
73,20150101,16:02,100107GG,BVE3413,11,M,2970,1,2970,6600,1,7212,2,00000000,20150102,12323,90266
74,20150101,11:44,100107GG,BVH3409,45,M,2340,1,2340,5200,2,3111,2,00000000,20150102,12323,90361
75,20150101,17:10,100107GG,BVH3416,40,M,1890,1,1890,4200,1,7238,2,00000000,20150102,12323,90349
76,20150101,11:01,100107GG,BVH3421,10,M,1890,1,1890,4200,1,7044,2,00000000,20150102,12323,90257
77,20150101,11:09,100107GG,BVH5307,10,M,1900,1,1900,3800,1,7049,2,00000000,20150102,12323,90258
78,20150101,14:08,100107GG,BVI1410,63,F,2430,1,2430,2700,1,7140,2,00000000,20150102,12323,90212
79,20150101,12:48,100107GG,BVI1410,70,F,900,1,900,2700,2,3135,2,00000000,20150102,12323,90268
80,20150101,11:26,100107GG,BVK3311,7,M,1710,1,1710,3800,2,3103,2,00000000,20150102,12323,90357
81,20150101,13:44,100107GG,BVK3451,26,M,1440,1,1440,3200,1,7127,2,00000000,20150102,12323,90208
82,20150101,12:42,100107GG,BVK3460,27,M,1440,1,1440,3200,1,7098,2,00000000,20150102,12323,90186
83,20150101,12:02,100107GG,BVL4402,11,M,2430,1,2430,5400,1,7080,2,00000000,20150102,12323,90158
84,20150101,11:56,100107GG,BVM3308,27,M,1710,1,1710,3800,1,7077,2,00000000,20150102,12323,90261
85,20150101,11:35,100107GG,BVM3421,10,M,1710,1,1710,3800,2,3106,2,00000000,20150102,12323,90358
86,20150101,12:51,100107GG,BVM3450,10,M,1890,1,1890,4200,2,3137,2,00000000,20150102,12323,90269
87,20150101,16:21,100107GG,BVM4415,6,M,1890,1,1890,4200,2,3178,2,00000000,20150102,12323,90363
88,20150101,16:30,100107GG,BVM5323,27,M,684,1,684,1900,1,7224,2,00000000,20150102,12323,90348
89,20150101,15:12,100107GG,BVQ0000,99,M,2700,1,2700,1000,1,7180,2,00000000,20150102,12323,68816
90,20150101,16:15,100107GG,BVS3319,27,S,1710,1,1710,3800,1,7219,2,00000000,20150102,12323,90229
91,20150101,12:45,100107GG,BVS4402,40,M,2538,1,2538,4700,1,7099,2,00000000,20150102,12323,90190
92,20150101,14:53,100107GG,BVS4402,40,S,2538,1,2538,4700,1,7168,2,00000000,20150102,12323,90217
93,20150101,11:18,100107GG,BVX3045,27,M,500,1,500,4700,1,7054,2,00000000,20150102,12323,90259
94,20150101,15:33,100107GG,GDC5304,27,36,2115,1,2115,4700,1,7193,2,00000000,20150102,12323,90224
95,20150101,15:33,100107GG,GDC5360,27,36,1368,1,1368,3800,1,7193,2,00000000,20150102,12323,90225
96,20150101,13:16,100107GG,GDC5401,40,36,1890,1,1890,4200,1,7113,2,00000000,20150102,12323,90366
97,20150101,11:30,100107GG,GDC5402,40,36,1900,1,1900,3800,2,3105,2,00000000,20150102,12323,90400
98,20150101,14:07,100107GG,GDC5403,1,38,2340,1,2340,5200,2,3149,2,00000000,20150102,12323,90429
99,20150101,12:29,100107GG,GDC5405,36,38,1710,1,1710,3800,1,7089,2,00000000,20150102,12323,90179

### salesテーブルから必要なものを取り出したもの
sales: 'member_id', 'part_no', 'color', 'color', 'size_id', 'unit_price', 'list_price', 'shop_id'

In [128]:
df_sales = df_sales_original.loc[:,['member_id', 'part_no', 'color', 
                         'size_id', 'unit_price', 'list_price', 'shop_id']]

### shop_idが重複しないように抽出

In [11]:
df_sales.head(1000).drop_duplicates('shop_id')

    member_id  part_no  color size_id  unit_price  list_price   shop_id
0    00000000  BVA4408      1       M        2240        6400  100003BV
20   00000000  EUA7434     80    24.5        7000       10000  100003EU
21   00000000  GAE1411      6      38        5600       16000  100003GA
23   00000000  GDC5406      6      38        1330        3800  100003GD
49   00000000  GGH2437      6      38        4900       14000  100003GG
50   00000000  GIA8407      1      38        2170        6200  100003GI
63   00000000  GTZ1412     35       F         630        1800  100003GT
64   00000000  GKG6436      5       M        9480       15800  100053GK
65   00000000  GMN4459     27       F        6650       19000  100053GM
67   00000000  ERE1157      7       M        2880       16000  100106AA
69   00000000  BVC1402     41       M        2115        4700  100107GG
242  00000000  BVK0408     52       M        1666        2800  100126GL
276  00000000  EKI1382      1       F        1600        2667  100241GA
460  00000000  AAA1406     27       L        5200       13000  100242AA
497  00000000  LFC2460     15       S        3950        7900  100245LH
521  00000000  GGC3412      1      38        9800       14000  100247GG
566  00000000  GDC5400     66      38        2660        3800  100248GD
712  00000000  BVA3400      1       S        2760        4600  100249GL
865  00000000  GAA5402      1    37.0       12600       18000  100253GA
902  00000000  GGC3408     27      40       11200       16000  100254GG
941  00000000  GVA1403     25    43.0        9000       15000  100256GV
944  00000000  BVQ9402     90       M       10000       10000  100286GL
945  00000000  EOA7404     30    24.5       20300       29000  100317EO

### 期間
sales_data: 20150101-20180131

In [49]:
#df_read_sls.drop_duplicates(subset = ['sales_date'])
print(df_sales.sales_date.max())
print(df_sales.sales_date.min())

20180131
20150101

### 会員数
member_id: 2400290---(2.40M)

In [50]:
len(df_sales['member_id'].unique())

2400290

### 有効会員番号数
有効会員番号：6105778件---(6.11M）

- 有効会員番号会員者数：2400289人---(2.40M)


無効会員番号：18214324件---(18.21M)

In [73]:
df_sales = df_sales.loc[:,['member_id', 'part_no', 'color', 'color', 
                         'size_id', 'unit_price', 'list_price', 'shop_id']]

In [78]:
print(len(df_sales.query("member_id == '00000000'")))
print(len(df_sales.query("member_id == '00000000'")['member_id'].unique()))
print(len(df_sales.query("member_id != '00000000'")))
print(len(df_sales.query("member_id != '00000000'")['member_id'].unique()))

18214324
1
6105778
2400289

## TABLE: sku
データ数：574412---(0.574M)
* What
    * 会社?? (sku.kaisya) (とりあえず7種類ある)
    * 部門?? (sku.bumon) (とりあえず1467種類ある)

In [157]:
cur = mysql.conn.cursor()
cur.execute('SELECT COUNT(*) FROM sku')

num_sku = cur.fetchall()
num_sku

[(574412,)]

In [159]:
sql = """
        SELECT * 
        FROM sku
        LIMIT 10000
      """
df = pd.read_sql(sql, mysql.conn)
df.head(100)

,part_no,color,size_id,kaisya,bumon,oyakbn,jan,ean,nw7,mntflg,crtymd,updymd,tanto,souflg,souymd
0,AAD04770,01,F,01,1028,1,4547349758057,0000000000000,102804770107,1,20140130,20140130,402408,0,20140130
1,AAD04770,08,F,01,1028,0,4547349758064,0000000000000,102804770807,1,20140130,20140130,402408,0,20140130
2,AAD04780,01,F,01,1028,1,4547349758071,0000000000000,102804780107,1,20140130,20140130,402408,0,20140130
3,AAD04780,08,F,01,1028,0,4547349758088,0000000000000,102804780807,1,20140130,20140130,402408,0,20140130
4,AAD04790,01,F,01,1028,1,4547349758095,0000000000000,102804790107,1,20140130,20140130,402408,0,20140130
5,AAD04790,08,F,01,1028,0,4547349758101,0000000000000,102804790807,1,20140130,20140130,402408,0,20140130
6,AAD04800,01,F,01,1028,1,4547349758118,0000000000000,102804800107,1,20140130,20140130,402408,0,20140130
7,AAD04800,08,F,01,1028,0,4547349758125,0000000000000,102804800807,1,20140130,20140130,402408,0,20140130
8,AAD04810,01,F,01,1028,1,4547349753311,0000000000000,102804810107,1,20140129,20140129,402408,0,20140129
9,AAD04810,08,F,01,1028,0,4547349753328,0000000000000,102804810807,1,20140129,20140129,402408,0,20140129
10,AAD04820,01,F,01,1028,1,4547349758132,0000000000000,102804820107,1,20140130,20140130,402408,0,20140130
11,AAD04820,08,F,01,1028,0,4547349758149,0000000000000,102804820807,1,20140130,20140130,402408,0,20140130
12,AAD04830,01,F,01,1028,1,4547349758156,0000000000000,102804830107,1,20140130,20140130,402408,0,20140130
13,AAD04830,08,F,01,1028,0,4547349758163,0000000000000,102804830807,1,20140130,20140130,402408,0,20140130
14,AAD04840,01,F,01,1028,1,4547349758170,0000000000000,102804840107,1,20140130,20140130,402408,0,20140130
15,AAD04840,08,F,01,1028,0,4547349758187,0000000000000,102804840807,1,20140130,20140130,402408,0,20140130
16,AAD04850,01,F,01,1028,1,4547349758194,0000000000000,102804850107,1,20140130,20140130,402408,0,20140130
17,AAD04850,08,F,01,1028,0,4547349758200,0000000000000,102804850807,1,20140130,20140130,402408,0,20140130
18,AAD04860,01,F,01,1028,1,4547349753335,0000000000000,102804860107,1,20140129,20140129,402408,0,20140129
19,AAD04860,08,F,01,1028,0,4547349753342,0000000000000,102804860807,1,20140129,20140129,402408,0,20140129
20,AAD04870,01,F,01,1028,1,4547349758217,0000000000000,102804870107,1,20140130,20140130,402408,0,20140130
21,AAD04870,08,F,01,1028,0,4547349758224,0000000000000,102804870807,1,20140130,20140130,402408,0,20140130
22,AAD04880,01,F,01,1028,1,4547349758231,0000000000000,102804880107,1,20140130,20140130,402408,0,20140130
23,AAD04880,08,F,01,1028,0,4547349758248,0000000000000,102804880807,1,20140130,20140130,402408,0,20140130
24,AAD04890,01,F,01,1028,1,4547349758255,0000000000000,102804890107,1,20140130,20140130,402408,0,20140130
25,AAD04890,08,F,01,1028,0,4547349758262,0000000000000,102804890807,1,20140130,20140130,402408,0,20140130
26,AAD04900,01,F,01,1028,1,4547349748522,0000000000000,102804900107,2,20140128,20140129,402408,0,20140128
27,AAD04900,08,F,01,1028,0,4547349748539,0000000000000,102804900807,2,20140128,20140129,402408,0,20140128
28,AAD04910,01,F,01,1028,1,4547349758279,0000000000000,102804910107,1,20140130,20140130,402408,0,20140130
29,AAD04910,08,F,01,1028,0,4547349758286,0000000000000,102804910807,1,20140130,20140130,402408,0,20140130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,AAD14090,40,F,01,1028,0,4547349759146,0000000000000,102814094007,1,20140130,20140130,402408,0,20140130
71,AAD64270,20,F,01,1028,1,4547443512685,0000000000000,102864272007,1,20140801,20140801,816916,0,20140801
72,AAD64270,44,F,01,1028,0,4547443512692,0000000000000,102864274407,1,20140801,20140801,816916,0,20140801
73,AAD64280,20,F,01,1028,1,4547443513408,0000000000000,102864282007,1,20140801,20140801,816916,0,20140801
74,AAD64280,44,F,01,1028,0,4547443513415,0000000000000,102864284407,1,20140801,20140801,816916,0,20140801
75,AAD64290,01,F,01,1028,1,4547443500859,0000000000000,102864290107,1,20140731,20140731,816916,0,20140731
76,AAD64290,07,F,01,1028,0,4547443500866,0000000000000,102864290707,1,20140731,20140731,816916,0,20140731
77,AAD74220,99,F,01,1028,0,4542373038694,0000000000000,102874229907,1,20141217,20141217,403471,0,20141217
78,AAD74230,01,F,01,1028,1,4547443924464,0000000000000,102874230107,1,20141117,20141117,403471,0,20141117
79,AAD74230,02,F,01,1028,0,4547443924471,0000000000000,102874230207,1,20141117,20141117,403471,0,20141117
80,AAD74230,03,F,01,1028,0,4547443924488,0000000000000,102874230307,1,20141117,20141117,403471,0,20141117
81,AAD74230,06,F,01,1028,0,4547443924495,0000000000000,102874230607,1,20141117,20141117,403471,0,20141117
82,AAD74230,07,F,01,1028,0,4547443924501,0000000000000,102874230707,1,20141117,20141117,403471,0,20141117
83,AAD74230,08,F,01,1028,0,4547443924518,0000000000000,102874230807,1,20141117,20141117,403471,0,20141117
84,AAD74230,09,F,01,1028,0,4547443924525,0000000000000,102874230907,1,20141117,20141117,403471,0,20141117
85,AAD74230,10,F,01,1028,0,4547443924532,0000000000000,102874231007,1,20141117,20141117,403471,0,20141117
86,AAD74230,20,F,01,1028,0,4547443924549,0000000000000,102874232007,1,20141117,20141117,403471,0,20141117
87,AAD74230,21,F,01,1028,0,4547443924556,0000000000000,102874232107,1,20141117,20141117,403471,0,20141117
88,AAD74230,27,F,01,1028,0,4547443924563,0000000000000,102874232707,1,20141117,20141117,403471,0,20141117
89,AAD74230,40,F,01,1028,0,4547443924570,0000000000000,102874234007,1,20141117,20141117,403471,0,20141117
90,AAD74230,41,F,01,1028,0,4547443924587,0000000000000,102874234107,1,20141117,20141117,403471,0,20141117
91,AAD74230,42,F,01,1028,0,4547443924594,0000000000000,102874234207,1,20141117,20141117,403471,0,20141117
92,AAD74230,44,F,01,1028,0,4547443924600,0000000000000,102874234407,1,20141117,20141117,403471,0,20141117
93,AAD74230,75,F,01,1028,0,4547443924617,0000000000000,102874237507,1,20141117,20141117,403471,0,20141117
94,AAD74230,99,F,01,1028,0,4547443924624,0000000000000,102874239907,1,20141117,20141117,403471,0,20141117
95,AAD74280,01,F,01,1028,1,4547443810552,0000000000000,102874280107,1,20141014,20141014,403471,0,20141014
96,AAD74280,02,F,01,1028,0,4547443810569,0000000000000,102874280207,1,20141014,20141014,403471,0,20141014
97,AAD74280,03,F,01,1028,0,4547443810576,0000000000000,102874280307,1,20141014,20141014,403471,0,20141014
98,AAD74280,06,F,01,1028,0,4547443810583,0000000000000,102874280607,1,20141014,20141014,403471,0,20141014
99,AAD74280,07,F,01,1028,0,4547443810590,0000000000000,102874280707,1,20141014,20141014,403471,0,20141014

In [1]:
import os.path

filename = 'jun_sku.csv'

if os.path.isfile(filename):
    df_sku = pd.read_csv(filename, header=None)
else:
    sql = """
            SELECT kaisya, bumon FROM sku
          """
    df_sku = pd.read_sql(sql, mysql.conn)

    df_sku.to_csv(filename)

NameError: name 'pd' is not defined

## TABLE: shop
データ数：3263
* Where
    * Main brand (shop.sbrand_code)
    * Status?? (shop.status)
    * Class1 (shop.class1_code) (Null値が入っているし，Null値入れて5種類)
    * Class2 (shop.class2_code) (Null値が入っているし，Null値入れて10種類)
    * Style (shop.style_code) (Null値が入ってるし，Null値入れて20種類)
    * Biz type?? (shop.biz_type) (直感的に店舗の規模感っぽい)
    * Deal class?? (shop.deal_class) (なんか使えそう)
    * **所在地情報がない**。Shop Nameから割り当てる??

### shopテーブルの確認

### メンズ・レディースブランド確認
- メンズ：AN (JUN RED)，GM (アダムエロぺオム）
- レディース：GA（アダムロペ），GD（ロペピクニック）

In [85]:
sql = """
    SELECT *
    FROM shop
    LIMIT 10000
    """
df = pd.read_sql(sql, mysql.conn)

df = df.sort_values('shop_code').drop_duplicates(subset = ['shop_code', 'sbrand_code'])

df = df.loc[:,['shop_code', 'sbrand_code',  'shop_name', 'floor']]#, 'style_code', 'biz_type', 'deal_class', 'floor', 'mod_date']]
#df[df.shop_name.str.contains('アダム エ ロペ')]
print(df[df.shop_code.str.startswith('216690')])
print(df[df.shop_code.str.startswith('216691')])
#print(df[df.shop_name.str.contains('三井アウトレットパーク多摩南大沢')])
#query('shop_code == 151090')

     shop_code sbrand_code     shop_name  floor
2833    216690          GD  熊本鶴屋　ロペピクニック  東館B1F
     shop_code sbrand_code shop_name floor
2834    216691          GG   熊本鶴屋　ロペ  本館2F

In [16]:
print("店舗数：", len(df.drop_duplicates(subset = ['shop_code'])))
print("ブランド数: ", len(df.drop_duplicates(subset = ['sbrand_code'])))

店舗数： 2385
ブランド数 93

In [196]:
sql = """
    SELECT sbrand_code, shop_name
    FROM shop
    LIMIT 10000
    """
df = pd.read_sql(sql, mysql.conn)
#df.query("shop_code == '100003'")
df = df.sort_values('sbrand_code').drop_duplicates(subset = 'shop_name')
print(df[df.shop_name.str.contains('レディース')])
print(df[df.shop_name.str.contains('メンズ')])
print(df.query("sbrand_code == 'KM'"))
#.query("sbrand_code != 'AA' and sbrand_code != 'AC'" )

     sbrand_code                shop_name
471           GA  FALKLAND 品川店　催事（レディース②）
2046          GA    催事：青山外苑前　レディース　アダムエロペ
3036          GA  催事：梅田ルクア　サンプルセール（レディース）
2494          GD   社内卸し：マリノアシティ　レディースブランド
466           GE   元町フォークランド　㈱ジュン　レディース消化
470           GG  FALKLAND 品川店　催事（レディース①）
473           NJ    FALKLAND 品川店 催事 レディース
512           RS            通信販売：楽天　レディース
     sbrand_code                   shop_name
152           AA            社内卸し：F/L本部　メンズＢ品
469           AA        FALKLAND　品川店　催事（メンズ）
465           AA        元町フォークランド　㈱ジュン　メンズ消化
513           AA                 通信販売：楽天　メンズ
1669          AN            有楽町阪急メンズ館　ジュンレッド
2103          BB           阪急メンズ東京　ＳＡＴＵＲＤＡＹＳ
3035          GM       催事：梅田ルクア　サンプルセール（メンズ）
2047          GM         催事：青山外苑前　メンズ　アダムエロペ
540           GM      通信販売：集英社　メンズノンノ　アダムエロペ
2234          KM     催事：　MAISON KITSUNE（メンズ）
3160          KM    大阪阪急　MAISON KITSUNE（メンズ）
2242          KM   有楽町阪急　MAISON KITSUNE（メンズ）
1074          LH   三井アウトレットパーク木更津　LE JUN メンズ
486           LH  通信販売：LE JUN メンズ　ジャドールオンライン
3125          UM     卸し：㈱阪急百貨店メンズ　ユナイテッドバンブー
     sbrand_code                       shop_name
2285          KM                          卸し：ｓｐ．
2286          KM                    卸し：ＧＯＬＤ　ＫＩＳＳ
2287          KM                    卸し：ｕｎｌｉｍｉｔｅｄ
2288          KM                    卸し：水戸　ｂｉｏｔｏｐ
2289          KM                      卸し：ＢＡＲＮＥＹＳ
2290          KM                   卸し：ＩＥＮＡ　ＳＬＯＶＥ
2291          KM                 卸し：ＴＯＭＯＲＲＯＷＬＡＮＤ
2231          KM                    KITSUNE　知人売掛
2233          KM                展示会受注（下館）　メゾンキツネ
2230          KM               卸し：Ｔａｋａｓｈｉｍａｙａ名古屋
2234          KM         催事：　MAISON KITSUNE（メンズ）
2235          KM        催事：新宿ルミネⅠ　MAISON KITSUNE
2236          KM            横浜ルミネ　MAISON KITSUNE
2292          KM                卸し：ＡＮＧＬＯＢＡＬ　ＳＨＯＰ
2237          KM      NEWoMAN　MAISON KITSUNE 新宿店
2293          KM                        卸し：ＡＮＤ　Ａ
2229          KM              卸し：ｍｉｒａｂｅｌｌａ　ｈｏｍｍｅ
2263          KM            卸し：ＡＤＤＩＴＩＯＮ　ＡＤＥＬＡＩＤＥ
2227          KM  通信販売　：　ZOZOTOWN MAISON KITSUNE
2215          KM                卸し ： 西武池袋　メゾンキツネ
2216          KM           卸し：　ＭＩＴＳＵＫＯＳＨＩ−Ｓｅｎｄａｉ
2279          KM             卸し：ＬＡＮＤ　ＯＦ　ＴＯＭＯＲＲＯＷ
2280          KM                   卸し：ｍａｒｔｉｎｉｑｕｅ
2281          KM                       卸し：ＲＥＣＯＲＤ
2282          KM                       卸し：Ｒｅｓｔｉｒ
3160          KM        大阪阪急　MAISON KITSUNE（メンズ）
2218          KM        卸し：　ＭＩＴＳＵＫＯＳＨＩＮｉｈｏｎｂａｓｈｉ
2219          KM               卸し：　ｍｉｄａｓ−ＬＩＣＡＶＯＵ
2220          KM                     卸し ： ＣＨＯＣＯＡ
2221          KM                 卸し ： ＳＷＥＥＴ　ＭＩＳＴ
...          ...                             ...
3147          KM                    卸し：ｄｉｃｅ＆ｄｉｃｅ
3154          KM                        卸し：ＰＨＡＲＥ
3157          KM        卸し：　ＭＩＴＳＵＫＯＳＨＩ−Ｍａｔｓｕｙａｍａ
3156          KM                         卸し：　井筒屋
2212          KM                卸し ： 大名古屋　リ・スタイル
2211          KM                 卸し ： ＡＮＮ　ＤＥ　ＡＲＫ
3162          KM                          卸し：岩田屋
2210          KM                 卸し：（株） 名古屋三越　栄店
2209          KM                       卸し：ＲＡＤＩＣＡ
3159          KM                 催事 ： 阪急大阪催事　キツネ
3163          KM                         卸し：梅田阪急
2208          KM                   卸し：Ｆｒｅｄ　Ｓｅｇａｌ
3155          KM     卸し ： ＡＮＤＹ　ＨＯＵＳＥ　ＨＹＰＥＲ　ＳＥＴＵＰ
3165          KM                         卸し：Ｒｉｃｋ
2207          KM                   卸し：ＩＳＥＴＡＮ　六本木
3158          KM        卸し：　ＭＩＴＳＵＫＯＳＨＩ−Ｔａｋａｍａｔｓｕ
3153          KM                       卸し：Ｃｈｅｒｒｙ
2206          KM             卸し：Ａｄａｍ　ｅｔ　Ｒｏｐｅ　有楽町
2205          KM            卸し：Ｊｕｓｔ　ｌｉｋｅ　ｈｏｎｅｙｅｅ
2204          KM                    卸し：ＥＬＬＥ　ＳＨＯＰ
3164          KM              卸し：Ｔａｋａｓｈｉｍａｙａ　京都店
2203          KM                        卸し：ＫＡＰＯＫ
2202          KM                 卸し：ＭＡＷ　ｏｆ　ＪＡＰＡＮ
3152          KM                       卸し：ＯＲＩＳＥＫ
3151          KM                   卸し：Ｖａｌｖｅａｔ　８１
3150          KM                          卸し：ｍｏｕ
2201          KM                  卸し：キーンパーセントヘルツ
3149          KM                      卸し：ＩＮＦＡＣＥＳ
3148          KM                        卸し：ＪＯＨＮＳ
2213          KM        卸し: ＰｏｐＵｐ　ＭＡＩＳＯＮ　ＫＩＴＳＵＮＥ

[145 rows x 2 columns]

### データ数取得

In [173]:
cur = mysql.conn.cursor()
sql = 'SELECT COUNT(*) FROM shop'
cur.execute(sql)
cur.fetchall()

[(3263,)]

In [202]:
cur = mysql.conn.cursor()
sql = """
    SELECT *
    FROM shop
    LIMIT 100
    """
cur.execute(sql)
cur.fetchall()

[('100000',
  'BH',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2008/05/09 12:49',
  '012885',
  '2008/05/09 12:56',
  '100001',
  'BH',
  '0',
  '999991',
  'UAA',
  '0',
  '6'),
 ('100000',
  'BJ',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:19',
  '010339',
  '2003/03/19 19:29',
  '100000',
  'BJ',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'BP',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:20',
  '010339',
  '2003/03/19 19:20',
  '100000',
  'BP',
  '0',
  '999991',
  'UBV',
  '0',
  '6'),
 ('100000',
  'BV',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:21',
  '010339',
  '2003/03/19 19:21',
  '100000',
  'BV',
  '0',
  '999991',
  'UBV',
  '0',
  '6'),
 ('100000',
  'BX',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:22',
  '010339',
  '2003/03/19 19:22',
  '100000',
  'BX',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'EK',
  '5',
  '知人売り\u3000ル・マガザン',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '007886',
  '2012/03/28 16:02',
  '007886',
  '2012/03/28 16:03',
  '100000',
  'EK',
  '1',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'ER',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2009/12/24 12:20',
  '014141',
  '2009/12/24 12:21',
  '100000',
  'ER',
  '',
  '999991',
  'UER',
  '0',
  '6'),
 ('100000',
  'EU',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:26',
  '014141',
  '2009/09/01 10:09',
  '100000',
  'EU',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'GA',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:27',
  '007886',
  '2012/03/28 16:01',
  '100000',
  'GA',
  '1',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'GC',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:29',
  '010339',
  '2003/03/19 19:40',
  '100000',
  'GC',
  '0',
  '999991',
  'UGC',
  '0',
  '6'),
 ('100000',
  'GD',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:40',
  '010339',
  '2003/03/19 19:40',
  '100000',
  'GD',
  '0',
  '999991',
  'UGD',
  '0',
  '6'),
 ('100000',
  'GE',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/19 19:58',
  '010339',
  '2003/03/22 19:18',
  '100000',
  'GE',
  '0',
  '999991',
  'UGC',
  '0',
  '6'),
 ('100000',
  'GF',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2007/12/29 10:20',
  '012885',
  '2007/12/29 10:24',
  '100000',
  'GF',
  '0',
  '999991',
  'UGG',
  '0',
  '6'),
 ('100000',
  'GG',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 19:17',
  '010339',
  '2003/03/22 19:18',
  '100000',
  'GG',
  '0',
  '999991',
  'UGG',
  '0',
  '6'),
 ('100000',
  'GH',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 19:17',
  '012885',
  '2006/10/02 22:00',
  '100000',
  'GH',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'GI',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2007/03/14 16:43',
  '014141',
  '2007/03/14 16:45',
  '100000',
  'GI',
  '',
  '999991',
  'UGD',
  '0',
  '6'),
 ('100000',
  'GL',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 19:18',
  '010339',
  '2003/03/22 19:18',
  '100000',
  'GL',
  '0',
  '999991',
  'UBV',
  '0',
  '6'),
 ('100000',
  'GT',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2007/03/14 16:46',
  '014141',
  '2007/03/14 16:48',
  '100000',
  'GT',
  '',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100000',
  'RR',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 19:21',
  '010339',
  '2003/03/22 19:21',
  '100000',
  'RR',
  '0',
  '999991',
  'U@@',
  '0',
  '6'),
 ('100000',
  'RS',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 19:54',
  '010339',
  '2003/03/22 19:54',
  '100000',
  'RS',
  '0',
  '999991',
  'U@@',
  '0',
  '6'),
 ('100000',
  'UM',
  '5',
  '知人売り：現金',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:03',
  '010339',
  '2003/03/22 20:03',
  '100000',
  'UM',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'BH',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2008/05/09 12:49',
  '012885',
  '2008/05/09 12:56',
  '100001',
  'BH',
  '0',
  '999991',
  'UAA',
  '0',
  '6'),
 ('100001',
  'BJ',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2010/07/30 12:41',
  '014141',
  '2010/07/30 12:44',
  '100001',
  'BJ',
  '',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'BP',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:04',
  '010339',
  '2003/03/22 20:04',
  '100001',
  'BP',
  '0',
  '999991',
  'UBV',
  '0',
  '6'),
 ('100001',
  'BV',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:04',
  '010339',
  '2003/03/22 20:05',
  '100001',
  'BV',
  '0',
  '999991',
  'UBV',
  '0',
  '6'),
 ('100001',
  'BX',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:05',
  '010339',
  '2003/03/22 20:05',
  '100001',
  'BX',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'EK',
  '5',
  '知人売り\u3000ル・マガザン',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '007886',
  '2012/03/28 16:05',
  '007886',
  '2012/03/28 16:06',
  '100001',
  'EK',
  '1',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'ER',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2009/12/24 12:19',
  '014141',
  '2009/12/24 12:20',
  '100001',
  'ER',
  '',
  '999991',
  'UER',
  '0',
  '6'),
 ('100001',
  'EU',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:06',
  '014141',
  '2009/09/01 10:09',
  '100001',
  'EU',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'GA',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:06',
  '007886',
  '2012/04/27 18:39',
  '100001',
  'GA',
  '1',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'GC',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:07',
  '010339',
  '2003/03/22 20:07',
  '100001',
  'GC',
  '0',
  '999991',
  'UGC',
  '0',
  '6'),
 ('100001',
  'GD',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:07',
  '010339',
  '2003/03/22 20:07',
  '100001',
  'GD',
  '0',
  '999991',
  'UGD',
  '0',
  '6'),
 ('100001',
  'GE',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:07',
  '010339',
  '2003/03/22 20:08',
  '100001',
  'GE',
  '0',
  '999991',
  'UGC',
  '0',
  '6'),
 ('100001',
  'GF',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:08',
  '010339',
  '2003/03/22 20:08',
  '100001',
  'GF',
  '0',
  '999991',
  'UGG',
  '0',
  '6'),
 ('100001',
  'GG',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:08',
  '007886',
  '2013/03/08 19:55',
  '100001',
  'GG',
  '0',
  '999991',
  'UGG',
  '0',
  '6'),
 ('100001',
  'GH',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:09',
  '012885',
  '2006/10/02 22:00',
  '100001',
  'GH',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'GI',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2007/03/14 16:40',
  '014141',
  '2007/03/14 16:42',
  '100001',
  'GI',
  '',
  '999991',
  'UGD',
  '0',
  '6'),
 ('100001',
  'GL',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:09',
  '010339',
  '2003/03/22 20:09',
  '100001',
  'GL',
  '0',
  '999991',
  'UBV',
  '0',
  '6'),
 ('100001',
  'GN',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:10',
  '010339',
  '2003/03/22 20:10',
  '100001',
  'GN',
  '0',
  '999991',
  'U@@',
  '0',
  '6'),
 ('100001',
  'GT',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2007/03/15 14:35',
  '012885',
  '2007/03/15 14:36',
  '100001',
  'GT',
  '',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100001',
  'RS',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:11',
  '010339',
  '2003/03/22 20:11',
  '100001',
  'RS',
  '0',
  '999991',
  'U@@',
  '0',
  '6'),
 ('100001',
  'UM',
  '5',
  '知人売り：掛売',
  '01',
  '08',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:11',
  '010339',
  '2003/03/22 20:12',
  '100001',
  'UM',
  '0',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100003',
  'BH',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2008/05/09 12:52',
  '012885',
  '2008/05/09 12:56',
  '100003',
  'BH',
  '0',
  '999992',
  'UAA',
  '0',
  '6'),
 ('100003',
  'BJ',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:13',
  '010339',
  '2003/03/22 20:13',
  '100003',
  'BJ',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'BP',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:13',
  '010339',
  '2003/03/22 20:13',
  '100003',
  'BP',
  '0',
  '999992',
  'UBV',
  '0',
  '6'),
 ('100003',
  'BV',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:13',
  '010339',
  '2003/03/22 20:14',
  '100003',
  'BV',
  '0',
  '999992',
  'UBV',
  '0',
  '6'),
 ('100003',
  'BX',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:14',
  '010339',
  '2003/03/22 20:14',
  '100003',
  'BX',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'EK',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '007886',
  '2012/06/06 18:23',
  '007886',
  '2012/06/06 18:29',
  '100003',
  'EK',
  '1',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'ER',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2009/12/24 12:16',
  '014141',
  '2009/12/24 12:17',
  '100003',
  'ER',
  '',
  '999992',
  'UER',
  '0',
  '6'),
 ('100003',
  'EU',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:15',
  '014141',
  '2009/09/01 10:09',
  '100003',
  'EU',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'GA',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:15',
  '007886',
  '2012/08/09 10:02',
  '100003',
  'GA',
  '1',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'GC',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:15',
  '010339',
  '2003/03/22 20:16',
  '100003',
  'GC',
  '0',
  '999992',
  'UGC',
  '0',
  '6'),
 ('100003',
  'GD',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:16',
  '010339',
  '2003/03/22 20:16',
  '100003',
  'GD',
  '0',
  '999992',
  'UGD',
  '0',
  '6'),
 ('100003',
  'GE',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:16',
  '010339',
  '2003/03/22 20:16',
  '100003',
  'GE',
  '0',
  '999992',
  'UGC',
  '0',
  '6'),
 ('100003',
  'GF',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2007/12/29 10:25',
  '012885',
  '2007/12/29 10:27',
  '100003',
  'GF',
  '',
  '999992',
  'UGG',
  '0',
  '6'),
 ('100003',
  'GG',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:17',
  '007886',
  '2013/05/09 16:45',
  '100003',
  'GG',
  '0',
  '999992',
  'UGG',
  '0',
  '6'),
 ('100003',
  'GH',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:17',
  '012885',
  '2006/10/02 22:00',
  '100003',
  'GH',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'GI',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2007/03/15 14:41',
  '012885',
  '2007/03/15 15:00',
  '100003',
  'GI',
  '',
  '999992',
  'UGD',
  '0',
  '6'),
 ('100003',
  'GL',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:17',
  '010339',
  '2003/04/04 15:59',
  '100003',
  'GL',
  '0',
  '999992',
  'UBV',
  '0',
  '6'),
 ('100003',
  'GN',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:18',
  '010339',
  '2003/03/22 20:18',
  '100003',
  'GN',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'GT',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2007/03/15 14:37',
  '012885',
  '2007/03/15 14:38',
  '100003',
  'GT',
  '',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100003',
  'RS',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:19',
  '010339',
  '2003/03/22 20:20',
  '100003',
  'RS',
  '0',
  '999992',
  'U@@',
  '0',
  '6'),
 ('100003',
  'UM',
  '5',
  '社員購入：給料引',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/22 20:20',
  '010339',
  '2003/03/22 20:20',
  '100003',
  'UM',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100004',
  'BH',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '012885',
  '2008/05/09 12:54',
  '012885',
  '2008/05/09 12:57',
  '100004',
  'BH',
  '0',
  '999992',
  'UAA',
  '0',
  '6'),
 ('100004',
  'BJ',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2010/07/30 12:44',
  '014141',
  '2010/07/30 12:45',
  '100004',
  'BJ',
  '',
  '999991',
  'UGA',
  '0',
  '6'),
 ('100004',
  'BP',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:33',
  '010339',
  '2003/03/24 10:33',
  '100004',
  'BP',
  '0',
  '999992',
  'UBV',
  '0',
  '6'),
 ('100004',
  'BV',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:34',
  '010339',
  '2003/03/24 10:34',
  '100004',
  'BV',
  '0',
  '999992',
  'UBV',
  '0',
  '6'),
 ('100004',
  'BX',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:34',
  '010339',
  '2003/03/24 10:37',
  '100004',
  'BX',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100004',
  'EK',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '007886',
  '2012/06/06 18:25',
  '007886',
  '2012/06/06 18:27',
  '100004',
  'EK',
  '1',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100004',
  'ER',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '014141',
  '2009/12/24 12:18',
  '014141',
  '2009/12/24 12:19',
  '100004',
  'ER',
  '',
  '999992',
  'UER',
  '0',
  '6'),
 ('100004',
  'EU',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:37',
  '014141',
  '2009/09/01 10:09',
  '100004',
  'EU',
  '0',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100004',
  'GA',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:38',
  '007886',
  '2012/06/06 18:21',
  '100004',
  'GA',
  '1',
  '999992',
  'UGA',
  '0',
  '6'),
 ('100004',
  'GC',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:38',
  '010339',
  '2003/03/24 10:39',
  '100004',
  'GC',
  '0',
  '999992',
  'UGC',
  '0',
  '6'),
 ('100004',
  'GD',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:39',
  '010339',
  '2003/03/24 10:40',
  '100004',
  'GD',
  '0',
  '999992',
  'UGD',
  '0',
  '6'),
 ('100004',
  'GE',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:39',
  '010339',
  '2003/03/24 10:39',
  '100004',
  'GE',
  '0',
  '999992',
  'UGC',
  '0',
  '6'),
 ('100004',
  'GF',
  '5',
  '社員購入：現金',
  '01',
  '03',
  'Z10',
  '99',
  '99',
  '0',
  '0',
  '',
  '0',
  '',
  '0',
  '',
  '',
  '010339',
  '2003/03/24 10:40',

### csvファイル作成 or 読み込み

In [4]:
import os.path

filename = 'jun_shop.csv'

if os.path.isfile(filename):
    df_shop = pd.read_csv(filename).iloc[:,1:]
    
else:
    sql = """
    SELECT sbrand_code, status, class1_code, class2_code, style_code, biz_type, deal_class, shop_name
    FROM shop
    """

    df_shop = pd.read_sql(sql, mysql.conn)
    df_shop.to_csv(filename)

### データ確認

In [5]:
#df_shop.query("sbrand_code = 'BH'")
df_shop.head(10)

,sbrand_code,status,class1_code,class2_code,style_code,biz_type,deal_class,shop_name
0,BH,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
1,BJ,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
2,BP,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
3,BV,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
4,BX,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
5,EK,5,1.0,8.0,Z10,99.0,99.0,知人売り ル・マガザン
6,ER,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
7,EU,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
8,GA,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金
9,GC,5,1.0,8.0,Z10,99.0,99.0,知人売り：現金

### 店舗数
2385店舗

In [213]:
print("店舗数：", len(df_shop.drop_duplicates(subset=['shop_code'])))
df_shop.drop_duplicates(subset=['shop_code'])#, 'sbrand_code'])

店舗数： 2385

,shop_code,sbrand_code,status,class1_code,class2_code,style_code,biz_type,deal_class,shop_name
0,100000,BH,5,01,08,Z10,99,99,知人売り：現金
21,100001,BH,5,01,08,Z10,99,99,知人売り：掛売
42,100003,BH,5,01,03,Z10,99,99,社員購入：給料引
63,100004,BH,5,01,03,Z10,99,99,社員購入：現金
84,100006,AA,5,01,99,Z99,99,99,その他： ジュンメン 贈呈
103,100007,BB,5,01,99,Z99,99,99,その他： サタデイズ 贈呈
123,100010,GA,5,02,99,Z99,99,02,青山アダムエロペ プレスルーム
124,100013,GG,5,01,07,Z09,02,02,社内卸し：白河フォークランド
128,100014,GX,5,01,03,Z10,99,99,社員購入：社員購入（現金）
131,100015,AQ,5,01,07,Z09,02,02,社内卸し：㈱フォークランド
152,100016,AA,5,02,07,Z09,99,02,社内卸し：F/L本部 メンズＢ品
153,100017,BY,5,01,07,Z09,02,02,社内卸し：(株)F/Lアウトレット
158,100018,GA,5,01,07,Z09,02,02,社内卸し：㈱F/Lアウトレット
160,100019,GT,5,01,07,Z09,02,02,社内卸し： ㈱F/L アダムエロペ
161,100020,AA,5,02,07,Z09,02,02,社内卸し：ジュンクラシックカントリークラブ
169,100025,AA,5,02,07,Z09,02,02,社内卸し：ロペ倶楽部
177,100026,AO,5,01,99,Z99,99,99,その他：ジュンアウトレット 贈呈２
188,100028,EQ,5,01,99,Z99,99,99,その他 REEFUR KIDS 贈呈
193,100029,EQ,5,01,99,Z99,99,99,その他 REEFUR KIDS 贈呈２
194,100030,ER,5,01,99,Z99,99,99,その他： ジュン＆ロペ贈呈3
195,100031,AA,5,99,99,Z99,99,99,その他：贈呈４
196,100032,BV,5,99,99,Z99,99,99,その他：贈呈５
197,100033,EN,5,99,99,Z99,99,99,その他：贈呈６
198,100034,GF,5,99,99,Z99,99,99,その他：贈呈７
199,100035,GV,5,99,99,Z99,99,99,その他：贈呈８
200,100037,PK,5,99,99,Z99,99,99,その他：贈呈９
201,100038,AQ,5,99,99,Z99,99,99,その他：贈呈１０
202,100043,AO,5,01,03,Z10,99,99,社員購入：現金
222,100044,AO,5,01,03,Z10,99,99,社員購入：給料引
241,100045,GW,5,01,08,Z10,99,99,知人売り：ロペマドモアゼル
...,...,...,...,...,...,...,...,...,...
3213,300444,NJ,5,99,02,Z10,01,02,通信販売 社員購入：ジャドール ナージー
3214,301318,EK,5,99,04,Z08,99,99,経費：アイルミネ アダムエロペ ル マガザン
3215,950001,GD,5,99,99,Z99,99,99,田町撮影用 ピクニック
3216,950002,LH,5,99,99,Z99,99,99,田町撮影用 ルジュン
3217,950003,BV,5,99,99,Z99,99,99,田町撮影用 ＶｉＳ
3218,950004,NJ,5,99,99,Z99,99,99,田町撮影用 ＮＥＲＧＹ
3219,960000,AN,5,99,99,Z99,99,99,田町撮影用 ジュン
3220,960001,GG,5,99,99,Z99,99,99,田町撮影用 ロペ
3221,960002,GA,5,99,99,Z99,99,99,田町撮影用 アダム１
3222,960003,EK,5,99,99,Z99,99,99,田町撮影用 アダム２
3223,960004,EC,5,99,99,Z99,99,99,田町撮影用 ジャドール
3224,960005,ZR,5,99,99,Z99,99,99,田町撮影用 ボンジュール
3225,960006,TS,5,99,99,Z99,99,99,田町撮影用 ザ・サリィ
3226,960007,ED,5,99,99,Z99,99,99,田町撮影用 メゾンキツネ
3227,960008,NJ,5,99,99,Z99,99,99,田町撮影用 NERGY
3228,960009,BB,5,99,99,Z99,99,99,田町撮影用 サタデーズサーフ
3229,979400,ZZ,5,01,99,Z99,99,99,ジュンカスタマーセンター
3230,979401,AA,5,01,99,Z99,99,99,GIDサイト申込み ジュンメン
3251,979402,AT,5,01,99,Z99,99,99,GIDサイト申込み ジュンクラブ
3252,979405,ZZ,5,99,99,Z99,99,99,A.P.C.カスタマーサービス
3253,980001,AA,5,99,99,Z99,99,99,福袋在庫調整用
3254,980002,GG,5,99,99,Z99,99,99,福袋在庫調整用
3255,980003,GC,5,99,99,Z99,99,99,福袋在庫調整用
3256,980004,GD,5,99,99,Z99,99,99,福袋在庫調整用
3257,980005,BV,5,99,99,Z99,99,99,福袋在庫調整用
3258,980006,GA,5,99,99,Z99,99,99,福袋在庫調整用
3259,980007,FL,5,99,99,Z99,99,99,福袋在庫調整用
3260,980008,ZR,5,99,99,Z99,99,99,福袋在庫調整用
3261,980009,LF,5,99,99,Z99,99,99,福袋在庫調整用
3262,980010,EO,5,99,99,Z99,99,99,福袋在庫調整用